
export interface ElementData {
  number: number;
  symbol: string;
  name: string;
  atomic_mass: number;
  category: string;
  group: number;
  period: number;
  phase: string;
  summary: string;
  electron_configuration: string;
  electron_shells: number[];
  color: string;
  electronegativity?: number;
  melting_point?: number;
  boiling_point?: number;
  density?: number;
  oxidation_states?: number[];
  common_compounds?: string[];
}

export const ELEMENTS: ElementData[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomic_mass: 1.008,
    category: "diatomic nonmetal",
    group: 1,
    period: 1,
    phase: "Gas",
    summary: "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table.",
    electron_configuration: "1s1",
    electron_shells: [1],
    color: "#D1D5DB",
    electronegativity: 2.20,
    melting_point: 14.01,
    boiling_point: 20.28,
    density: 0.00008988,
    oxidation_states: [1, -1],
    common_compounds: ["H2O", "HCl", "CH4", "NH3"]
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomic_mass: 4.0026,
    category: "noble gas",
    group: 18,
    period: 1,
    phase: "Gas",
    summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
    electron_configuration: "1s2",
    electron_shells: [2],
    color: "#FDE68A",
    electronegativity: undefined,
    melting_point: 0.95,
    boiling_point: 4.22,
    density: 0.0001785,
    oxidation_states: [0],
    common_compounds: ["None (Inert)"]
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomic_mass: 6.94,
    category: "alkali metal",
    group: 1,
    period: 2,
    phase: "Solid",
    summary: "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
    electron_configuration: "[He] 2s1",
    electron_shells: [2, 1],
    color: "#F87171",
    electronegativity: 0.98,
    melting_point: 453.65,
    boiling_point: 1603,
    density: 0.534,
    oxidation_states: [1],
    common_compounds: ["Li2O", "LiOH", "LiCl", "Li2CO3"]
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomic_mass: 9.0122,
    category: "alkaline earth metal",
    group: 2,
    period: 2,
    phase: "Solid",
    summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    electron_configuration: "[He] 2s2",
    electron_shells: [2, 2],
    color: "#FBBF24",
    electronegativity: 1.57,
    melting_point: 1560,
    boiling_point: 2742,
    density: 1.85,
    oxidation_states: [2],
    common_compounds: ["BeO", "BeCl2", "Be(OH)2"]
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomic_mass: 10.81,
    category: "metalloid",
    group: 13,
    period: 2,
    phase: "Solid",
    summary: "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar System and in the Earth's crust.",
    electron_configuration: "[He] 2s2 2p1",
    electron_shells: [2, 3],
    color: "#34D399",
    electronegativity: 2.04,
    melting_point: 2349,
    boiling_point: 4273,
    density: 2.08,
    oxidation_states: [3],
    common_compounds: ["B2O3", "H3BO3", "BF3", "NaBH4"]
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomic_mass: 12.011,
    category: "polyatomic nonmetal",
    group: 14,
    period: 2,
    phase: "Solid",
    summary: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
    electron_configuration: "[He] 2s2 2p2",
    electron_shells: [2, 4],
    color: "#60A5FA",
    electronegativity: 2.55,
    melting_point: 3823,
    boiling_point: 4300,
    density: 2.267,
    oxidation_states: [4, 2, -4],
    common_compounds: ["CO2", "CO", "CH4", "C6H12O6"]
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomic_mass: 14.007,
    category: "diatomic nonmetal",
    group: 15,
    period: 2,
    phase: "Gas",
    summary: "Nitrogen is the chemical element with the symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    electron_configuration: "[He] 2s2 2p3",
    electron_shells: [2, 5],
    color: "#818CF8",
    electronegativity: 3.04,
    melting_point: 63.15,
    boiling_point: 77.36,
    density: 0.0012506,
    oxidation_states: [5, 4, 3, 2, 1, -1, -2, -3],
    common_compounds: ["NH3", "HNO3", "N2O", "NO2"]
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomic_mass: 15.999,
    category: "diatomic nonmetal",
    group: 16,
    period: 2,
    phase: "Gas",
    summary: "Oxygen is the chemical element with the symbol O and atomic number 8. It is a member of the chalcogen group in the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.",
    electron_configuration: "[He] 2s2 2p4",
    electron_shells: [2, 6],
    color: "#A78BFA",
    electronegativity: 3.44,
    melting_point: 54.36,
    boiling_point: 90.20,
    density: 0.001429,
    oxidation_states: [-2],
    common_compounds: ["H2O", "CO2", "O3", "SiO2"]
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomic_mass: 18.998,
    category: "diatomic nonmetal",
    group: 17,
    period: 2,
    phase: "Gas",
    summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the most electronegative element and is extremely reactive: almost all other elements, including some noble gases, form compounds with fluorine.",
    electron_configuration: "[He] 2s2 2p5",
    electron_shells: [2, 7],
    color: "#F472B6",
    electronegativity: 3.98,
    melting_point: 53.48,
    boiling_point: 85.03,
    density: 0.001696,
    oxidation_states: [-1],
    common_compounds: ["HF", "NaF", "CaF2", "SF6"]
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomic_mass: 20.180,
    category: "noble gas",
    group: 18,
    period: 2,
    phase: "Gas",
    summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
    electron_configuration: "[He] 2s2 2p6",
    electron_shells: [2, 8],
    color: "#FDE68A",
    electronegativity: undefined,
    melting_point: 24.56,
    boiling_point: 27.07,
    density: 0.0008999,
    oxidation_states: [0],
    common_compounds: ["None (Inert)"]
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomic_mass: 22.990,
    category: "alkali metal",
    group: 1,
    period: 3,
    phase: "Solid",
    summary: "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal. Sodium is an alkali metal, being in group 1 of the periodic table.",
    electron_configuration: "[Ne] 3s1",
    electron_shells: [2, 8, 1],
    color: "#F87171",
    electronegativity: 0.93,
    melting_point: 370.944,
    boiling_point: 1156.09,
    density: 0.968,
    oxidation_states: [1]
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomic_mass: 24.305,
    category: "alkaline earth metal",
    group: 2,
    period: 3,
    phase: "Solid",
    summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
    electron_configuration: "[Ne] 3s2",
    electron_shells: [2, 8, 2],
    color: "#FBBF24",
    electronegativity: 1.31,
    melting_point: 923,
    boiling_point: 1363,
    density: 1.738,
    oxidation_states: [2]
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminum",
    atomic_mass: 26.982,
    category: "post-transition metal",
    group: 13,
    period: 3,
    phase: "Solid",
    summary: "Aluminium is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic and ductile metal in the boron group.",
    electron_configuration: "[Ne] 3s2 3p1",
    electron_shells: [2, 8, 3],
    color: "#94A3B8",
    electronegativity: 1.61,
    melting_point: 933.47,
    boiling_point: 2743,
    density: 2.70,
    oxidation_states: [3]
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomic_mass: 28.085,
    category: "metalloid",
    group: 14,
    period: 3,
    phase: "Solid",
    summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-gray metallic luster; and it is a tetravalent metalloid and semiconductor.",
    electron_configuration: "[Ne] 3s2 3p2",
    electron_shells: [2, 8, 4],
    color: "#34D399",
    electronegativity: 1.90,
    melting_point: 1687,
    boiling_point: 3538,
    density: 2.329,
    oxidation_states: [4, 2, -4]
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomic_mass: 30.974,
    category: "polyatomic nonmetal",
    group: 15,
    period: 3,
    phase: "Solid",
    summary: "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms, white phosphorus and red phosphorus, but because it is highly reactive, phosphorus is never found as a free element on Earth.",
    electron_configuration: "[Ne] 3s2 3p3",
    electron_shells: [2, 8, 5],
    color: "#60A5FA",
    electronegativity: 2.19,
    melting_point: 317.3,
    boiling_point: 553.7,
    density: 1.823,
    oxidation_states: [5, 4, 3, 2, 1, -1, -2, -3]
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomic_mass: 32.06,
    category: "polyatomic nonmetal",
    group: 16,
    period: 3,
    phase: "Solid",
    summary: "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8.",
    electron_configuration: "[Ne] 3s2 3p4",
    electron_shells: [2, 8, 6],
    color: "#A78BFA",
    electronegativity: 2.58,
    melting_point: 388.36,
    boiling_point: 717.8,
    density: 2.07,
    oxidation_states: [6, 4, 2, -2]
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomic_mass: 35.45,
    category: "diatomic nonmetal",
    group: 17,
    period: 3,
    phase: "Gas",
    summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.",
    electron_configuration: "[Ne] 3s2 3p5",
    electron_shells: [2, 8, 7],
    color: "#F472B6",
    electronegativity: 3.16,
    melting_point: 171.6,
    boiling_point: 239.11,
    density: 0.0032,
    oxidation_states: [7, 5, 3, 1, -1]
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomic_mass: 39.948,
    category: "noble gas",
    group: 18,
    period: 3,
    phase: "Gas",
    summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934%.",
    electron_configuration: "[Ne] 3s2 3p6",
    electron_shells: [2, 8, 8],
    color: "#FDE68A",
    electronegativity: undefined,
    melting_point: 83.81,
    boiling_point: 87.30,
    density: 0.001784,
    oxidation_states: [0]
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomic_mass: 39.098,
    category: "alkali metal",
    group: 1,
    period: 4,
    phase: "Solid",
    summary: "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives. In the periodic table, potassium is one of the alkali metals.",
    electron_configuration: "[Ar] 4s1",
    electron_shells: [2, 8, 8, 1],
    color: "#F87171",
    electronegativity: 0.82,
    melting_point: 336.7,
    boiling_point: 1032,
    density: 0.862,
    oxidation_states: [1]
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomic_mass: 40.078,
    category: "alkaline earth metal",
    group: 2,
    period: 4,
    phase: "Solid",
    summary: "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
    electron_configuration: "[Ar] 4s2",
    electron_shells: [2, 8, 8, 2],
    color: "#FBBF24",
    electronegativity: 1.00,
    melting_point: 1115,
    boiling_point: 1757,
    density: 1.54,
    oxidation_states: [2]
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomic_mass: 44.956,
    category: "transition metal",
    group: 3,
    period: 4,
    phase: "Solid",
    summary: "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element, together with yttrium and the lanthanides.",
    electron_configuration: "[Ar] 3d1 4s2",
    electron_shells: [2, 8, 9, 2],
    color: "#94A3B8",
    electronegativity: 1.36,
    melting_point: 1814,
    boiling_point: 3109,
    density: 2.985,
    oxidation_states: [3]
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomic_mass: 47.867,
    category: "transition metal",
    group: 4,
    period: 4,
    phase: "Solid",
    summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.",
    electron_configuration: "[Ar] 3d2 4s2",
    electron_shells: [2, 8, 10, 2],
    color: "#94A3B8",
    electronegativity: 1.54,
    melting_point: 1941,
    boiling_point: 3560,
    density: 4.506,
    oxidation_states: [4, 3, 2]
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomic_mass: 50.942,
    category: "transition metal",
    group: 5,
    period: 4,
    phase: "Solid",
    summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, malleable transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer somewhat stabilizes the free metal against further oxidation.",
    electron_configuration: "[Ar] 3d3 4s2",
    electron_shells: [2, 8, 11, 2],
    color: "#94A3B8",
    electronegativity: 1.63,
    melting_point: 2183,
    boiling_point: 3680,
    density: 6.11,
    oxidation_states: [5, 4, 3, 2]
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomic_mass: 51.996,
    category: "transition metal",
    group: 6,
    period: 4,
    phase: "Solid",
    summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6. It is a steely-grey, lustrous, hard and brittle transition metal.",
    electron_configuration: "[Ar] 3d5 4s1",
    electron_shells: [2, 8, 13, 1],
    color: "#94A3B8",
    electronegativity: 1.66,
    melting_point: 2180,
    boiling_point: 2944,
    density: 7.15,
    oxidation_states: [6, 3, 2]
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomic_mass: 54.938,
    category: "transition metal",
    group: 7,
    period: 4,
    phase: "Solid",
    summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
    electron_configuration: "[Ar] 3d5 4s2",
    electron_shells: [2, 8, 13, 2],
    color: "#94A3B8",
    electronegativity: 1.55,
    melting_point: 1519,
    boiling_point: 2334,
    density: 7.21,
    oxidation_states: [7, 6, 4, 3, 2]
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomic_mass: 55.845,
    category: "transition metal",
    group: 8,
    period: 4,
    phase: "Solid",
    summary: "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table. It is, by mass, the most common element on Earth, right in front of oxygen, forming much of Earth's outer and inner core.",
    electron_configuration: "[Ar] 3d6 4s2",
    electron_shells: [2, 8, 14, 2],
    color: "#94A3B8",
    electronegativity: 1.83,
    melting_point: 1811,
    boiling_point: 3134,
    density: 7.874,
    oxidation_states: [3, 2]
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomic_mass: 58.933,
    category: "transition metal",
    group: 9,
    period: 4,
    phase: "Solid",
    summary: "Cobalt is a chemical element with symbol Co and atomic number 27. Like iron, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
    electron_configuration: "[Ar] 3d7 4s2",
    electron_shells: [2, 8, 15, 2],
    color: "#94A3B8",
    electronegativity: 1.88,
    melting_point: 1768,
    boiling_point: 3200,
    density: 8.90,
    oxidation_states: [3, 2]
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomic_mass: 58.693,
    category: "transition metal",
    group: 10,
    period: 4,
    phase: "Solid",
    summary: "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.",
    electron_configuration: "[Ar] 3d8 4s2",
    electron_shells: [2, 8, 16, 2],
    color: "#94A3B8",
    electronegativity: 1.91,
    melting_point: 1728,
    boiling_point: 3186,
    density: 8.908,
    oxidation_states: [3, 2]
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomic_mass: 63.546,
    category: "transition metal",
    group: 11,
    period: 4,
    phase: "Solid",
    summary: "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a pinkish-orange color.",
    electron_configuration: "[Ar] 3d10 4s1",
    electron_shells: [2, 8, 18, 1],
    color: "#94A3B8",
    electronegativity: 1.90,
    melting_point: 1357.77,
    boiling_point: 2835,
    density: 8.96,
    oxidation_states: [2, 1]
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomic_mass: 65.38,
    category: "transition metal",
    group: 12,
    period: 4,
    phase: "Solid",
    summary: "Zinc is a chemical element with symbol Zn and atomic number 30. Zinc is a slightly brittle metal at room temperature and has a blue-silvery appearance when oxidation is removed. It is the first element in group 12 of the periodic table.",
    electron_configuration: "[Ar] 3d10 4s2",
    electron_shells: [2, 8, 18, 2],
    color: "#94A3B8",
    electronegativity: 1.65,
    melting_point: 692.68,
    boiling_point: 1180,
    density: 7.14,
    oxidation_states: [2]
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomic_mass: 69.723,
    category: "post-transition metal",
    group: 13,
    period: 4,
    phase: "Solid",
    summary: "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium is a soft, silvery blue metal at standard temperature and pressure, a brittle solid at low temperatures, and a liquid at temperatures greater than 29.76 °C.",
    electron_configuration: "[Ar] 3d10 4s2 4p1",
    electron_shells: [2, 8, 18, 3],
    color: "#94A3B8"
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomic_mass: 72.63,
    category: "metalloid",
    group: 14,
    period: 4,
    phase: "Solid",
    summary: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard-brittle, grayish-white metalloid in the carbon group, chemically similar to its group neighbors silicon and tin.",
    electron_configuration: "[Ar] 3d10 4s2 4p2",
    electron_shells: [2, 8, 18, 4],
    color: "#34D399"
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomic_mass: 74.922,
    category: "metalloid",
    group: 15,
    period: 4,
    phase: "Solid",
    summary: "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.",
    electron_configuration: "[Ar] 3d10 4s2 4p3",
    electron_shells: [2, 8, 18, 5],
    color: "#34D399"
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomic_mass: 78.971,
    category: "polyatomic nonmetal",
    group: 16,
    period: 4,
    phase: "Solid",
    summary: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal (more rarely considered a metalloid) with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium.",
    electron_configuration: "[Ar] 3d10 4s2 4p4",
    electron_shells: [2, 8, 18, 6],
    color: "#60A5FA"
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomic_mass: 79.904,
    category: "diatomic nonmetal",
    group: 17,
    period: 4,
    phase: "Liquid",
    summary: "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.",
    electron_configuration: "[Ar] 3d10 4s2 4p5",
    electron_shells: [2, 8, 18, 7],
    color: "#F472B6"
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomic_mass: 83.798,
    category: "noble gas",
    group: 18,
    period: 4,
    phase: "Gas",
    summary: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere.",
    electron_configuration: "[Ar] 3d10 4s2 4p6",
    electron_shells: [2, 8, 18, 8],
    color: "#FDE68A"
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomic_mass: 85.468,
    category: "alkali metal",
    group: 1,
    period: 5,
    phase: "Solid",
    summary: "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with an atomic mass of 85.4678.",
    electron_configuration: "[Kr] 5s1",
    electron_shells: [2, 8, 18, 8, 1],
    color: "#F87171"
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomic_mass: 87.62,
    category: "alkaline earth metal",
    group: 2,
    period: 5,
    phase: "Solid",
    summary: "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically.",
    electron_configuration: "[Kr] 5s2",
    electron_shells: [2, 8, 18, 8, 2],
    color: "#FBBF24"
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomic_mass: 88.906,
    category: "transition metal",
    group: 3,
    period: 5,
    phase: "Solid",
    summary: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a \"rare-earth element\".",
    electron_configuration: "[Kr] 4d1 5s2",
    electron_shells: [2, 8, 18, 9, 2],
    color: "#94A3B8"
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomic_mass: 91.224,
    category: "transition metal",
    group: 4,
    period: 5,
    phase: "Solid",
    summary: "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium.",
    electron_configuration: "[Kr] 4d2 5s2",
    electron_shells: [2, 8, 18, 10, 2],
    color: "#94A3B8"
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomic_mass: 92.906,
    category: "transition metal",
    group: 5,
    period: 5,
    phase: "Solid",
    summary: "Niobium, formerly known as columbium, is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, crystalline, ductile transition metal, often found in the minerals pyrochlore and columbite.",
    electron_configuration: "[Kr] 4d4 5s1",
    electron_shells: [2, 8, 18, 12, 1],
    color: "#94A3B8"
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomic_mass: 95.95,
    category: "transition metal",
    group: 6,
    period: 5,
    phase: "Solid",
    summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek molybdos, meaning lead, since its ores were confused with lead ores.",
    electron_configuration: "[Kr] 4d5 5s1",
    electron_shells: [2, 8, 18, 13, 1],
    color: "#94A3B8"
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomic_mass: 98,
    category: "transition metal",
    group: 7,
    period: 5,
    phase: "Solid",
    summary: "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive; none are stable, excluding the fully ionized state of 97Tc.",
    electron_configuration: "[Kr] 4d5 5s2",
    electron_shells: [2, 8, 18, 13, 2],
    color: "#94A3B8"
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomic_mass: 101.07,
    category: "transition metal",
    group: 8,
    period: 5,
    phase: "Solid",
    summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.",
    electron_configuration: "[Kr] 4d7 5s1",
    electron_shells: [2, 8, 18, 15, 1],
    color: "#94A3B8"
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomic_mass: 102.91,
    category: "transition metal",
    group: 9,
    period: 5,
    phase: "Solid",
    summary: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal. It is a noble metal and a member of the platinum group.",
    electron_configuration: "[Kr] 4d8 5s1",
    electron_shells: [2, 8, 18, 16, 1],
    color: "#94A3B8"
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomic_mass: 106.42,
    category: "transition metal",
    group: 10,
    period: 5,
    phase: "Solid",
    summary: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston.",
    electron_configuration: "[Kr] 4d10",
    electron_shells: [2, 8, 18, 18],
    color: "#94A3B8"
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomic_mass: 107.87,
    category: "transition metal",
    group: 11,
    period: 5,
    phase: "Solid",
    summary: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    electron_configuration: "[Kr] 4d10 5s1",
    electron_shells: [2, 8, 18, 18, 1],
    color: "#94A3B8"
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomic_mass: 112.41,
    category: "transition metal",
    group: 12,
    period: 5,
    phase: "Solid",
    summary: "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, silvery-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
    electron_configuration: "[Kr] 4d10 5s2",
    electron_shells: [2, 8, 18, 18, 2],
    color: "#94A3B8"
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomic_mass: 114.82,
    category: "post-transition metal",
    group: 13,
    period: 5,
    phase: "Solid",
    summary: "Indium is a chemical element with symbol In and atomic number 49. Indium is a post-transition metal that makes up 0.21 parts per million of the Earth's crust. Indium is a very soft, malleable and easily fusible metal.",
    electron_configuration: "[Kr] 4d10 5s2 5p1",
    electron_shells: [2, 8, 18, 18, 3],
    color: "#94A3B8"
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomic_mass: 118.71,
    category: "post-transition metal",
    group: 14,
    period: 5,
    phase: "Solid",
    summary: "Tin is a chemical element with symbol Sn and atomic number 50. Tin is a silvery-white metal with a faint yellow hue. Tin, like indium, is soft enough to be cut without much force.",
    electron_configuration: "[Kr] 4d10 5s2 5p2",
    electron_shells: [2, 8, 18, 18, 4],
    color: "#94A3B8"
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomic_mass: 121.76,
    category: "metalloid",
    group: 15,
    period: 5,
    phase: "Solid",
    summary: "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.",
    electron_configuration: "[Kr] 4d10 5s2 5p3",
    electron_shells: [2, 8, 18, 18, 5],
    color: "#34D399"
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomic_mass: 127.6,
    category: "metalloid",
    group: 16,
    period: 5,
    phase: "Solid",
    summary: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur, all three of which are chalcogens.",
    electron_configuration: "[Kr] 4d10 5s2 5p4",
    electron_shells: [2, 8, 18, 18, 6],
    color: "#34D399"
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    atomic_mass: 126.9,
    category: "diatomic nonmetal",
    group: 17,
    period: 5,
    phase: "Solid",
    summary: "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a semi-lustrous, non-metallic solid at standard conditions that melts to form a deep violet liquid at 114 degrees Celsius.",
    electron_configuration: "[Kr] 4d10 5s2 5p5",
    electron_shells: [2, 8, 18, 18, 7],
    color: "#F472B6"
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomic_mass: 131.29,
    category: "noble gas",
    group: 18,
    period: 5,
    phase: "Gas",
    summary: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts.",
    electron_configuration: "[Kr] 4d10 5s2 5p6",
    electron_shells: [2, 8, 18, 18, 8],
    color: "#FDE68A"
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    atomic_mass: 132.91,
    category: "alkali metal",
    group: 1,
    period: 6,
    phase: "Solid",
    summary: "Caesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28.5 °C, which makes it one of only five elemental metals that are liquid at or near room temperature.",
    electron_configuration: "[Xe] 6s1",
    electron_shells: [2, 8, 18, 18, 8, 1],
    color: "#F87171"
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomic_mass: 137.33,
    category: "alkaline earth metal",
    group: 2,
    period: 6,
    phase: "Solid",
    summary: "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.",
    electron_configuration: "[Xe] 6s2",
    electron_shells: [2, 8, 18, 18, 8, 2],
    color: "#FBBF24"
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomic_mass: 138.91,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes slowly when exposed to air and is soft enough to be cut with a knife.",
    electron_configuration: "[Xe] 5d1 6s2",
    electron_shells: [2, 8, 18, 18, 9, 2],
    color: "#A78BFA"
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomic_mass: 140.12,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile, and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.",
    electron_configuration: "[Xe] 4f1 5d1 6s2",
    electron_shells: [2, 8, 18, 19, 9, 2],
    color: "#A78BFA"
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomic_mass: 140.91,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal, valued for its magnetic, electrical, chemical, and optical properties.",
    electron_configuration: "[Xe] 4f3 6s2",
    electron_shells: [2, 8, 18, 21, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomic_mass: 144.24,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach.",
    electron_configuration: "[Xe] 4f4 6s2",
    electron_shells: [2, 8, 18, 22, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomic_mass: 145,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500-600 grams naturally occurring in Earth's crust at any given time.",
    electron_configuration: "[Xe] 4f5 6s2",
    electron_shells: [2, 8, 18, 23, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomic_mass: 150.36,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air. Being a typical member of the lanthanide series, samarium usually possesses the oxidation state +3.",
    electron_configuration: "[Xe] 4f6 6s2",
    electron_shells: [2, 8, 18, 24, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomic_mass: 151.96,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Europium is a chemical element with symbol Eu and atomic number 63. Europium is the most reactive lanthanide, having to be stored under an inert fluid to protect it from atmospheric oxygen or moisture.",
    electron_configuration: "[Xe] 4f7 6s2",
    electron_shells: [2, 8, 18, 25, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomic_mass: 157.25,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white metal when oxidation is removed. It is only slightly malleable and is a ductile rare-earth metal.",
    electron_configuration: "[Xe] 4f7 5d1 6s2",
    electron_shells: [2, 8, 18, 25, 9, 2],
    color: "#A78BFA"
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomic_mass: 158.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. Terbium is never found in nature as a free element.",
    electron_configuration: "[Xe] 4f9 6s2",
    electron_shells: [2, 8, 18, 27, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomic_mass: 162.5,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare-earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime.",
    electron_configuration: "[Xe] 4f10 6s2",
    electron_shells: [2, 8, 18, 28, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomic_mass: 164.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element. Holmium was discovered by Swedish chemist Per Teodor Cleve.",
    electron_configuration: "[Xe] 4f11 6s2",
    electron_shells: [2, 8, 18, 29, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomic_mass: 167.26,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.",
    electron_configuration: "[Xe] 4f12 6s2",
    electron_shells: [2, 8, 18, 30, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomic_mass: 168.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds.",
    electron_configuration: "[Xe] 4f13 6s2",
    electron_shells: [2, 8, 18, 31, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomic_mass: 173.05,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state.",
    electron_configuration: "[Xe] 4f14 6s2",
    electron_shells: [2, 8, 18, 32, 8, 2],
    color: "#A78BFA"
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomic_mass: 174.97,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    summary: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series, and it is traditionally counted among the rare earths.",
    electron_configuration: "[Xe] 4f14 5d1 6s2",
    electron_shells: [2, 8, 18, 32, 9, 2],
    color: "#A78BFA"
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomic_mass: 178.49,
    category: "transition metal",
    group: 4,
    period: 6,
    phase: "Solid",
    summary: "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.",
    electron_configuration: "[Xe] 4f14 5d2 6s2",
    electron_shells: [2, 8, 18, 32, 10, 2],
    color: "#94A3B8"
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomic_mass: 180.95,
    category: "transition metal",
    group: 5,
    period: 6,
    phase: "Solid",
    summary: "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, a figure from Greek mythology. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.",
    electron_configuration: "[Xe] 4f14 5d3 6s2",
    electron_shells: [2, 8, 18, 32, 11, 2],
    color: "#94A3B8"
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomic_mass: 183.84,
    category: "transition metal",
    group: 6,
    period: 6,
    phase: "Solid",
    summary: "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. Tungsten is a rare metal found naturally on Earth almost exclusively as compounds with other elements.",
    electron_configuration: "[Xe] 4f14 5d4 6s2",
    electron_shells: [2, 8, 18, 32, 12, 2],
    color: "#94A3B8"
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomic_mass: 186.21,
    category: "transition metal",
    group: 7,
    period: 6,
    phase: "Solid",
    summary: "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion, rhenium is one of the rarest elements in the Earth's crust.",
    electron_configuration: "[Xe] 4f14 5d5 6s2",
    electron_shells: [2, 8, 18, 32, 13, 2],
    color: "#94A3B8"
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomic_mass: 190.23,
    category: "transition metal",
    group: 8,
    period: 6,
    phase: "Solid",
    summary: "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.",
    electron_configuration: "[Xe] 4f14 5d6 6s2",
    electron_shells: [2, 8, 18, 32, 14, 2],
    color: "#94A3B8"
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomic_mass: 192.22,
    category: "transition metal",
    group: 9,
    period: 6,
    phase: "Solid",
    summary: "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is generally credited with being the second densest element (after osmium).",
    electron_configuration: "[Xe] 4f14 5d7 6s2",
    electron_shells: [2, 8, 18, 32, 15, 2],
    color: "#94A3B8"
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomic_mass: 195.08,
    category: "transition metal",
    group: 10,
    period: 6,
    phase: "Solid",
    summary: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silver-white transition metal. Its name is derived from the Spanish term platina, which is literally translated into \"little silver\".",
    electron_configuration: "[Xe] 4f14 5d9 6s1",
    electron_shells: [2, 8, 18, 32, 17, 1],
    color: "#94A3B8"
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomic_mass: 196.97,
    category: "transition metal",
    group: 11,
    period: 6,
    phase: "Solid",
    summary: "Gold is a chemical element with symbol Au and atomic number 79, making it one of the higher atomic number elements that occur naturally. In its pure form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
    electron_configuration: "[Xe] 4f14 5d10 6s1",
    electron_shells: [2, 8, 18, 32, 18, 1],
    color: "#FBBF24"
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomic_mass: 200.59,
    category: "transition metal",
    group: 12,
    period: 6,
    phase: "Liquid",
    summary: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.",
    electron_configuration: "[Xe] 4f14 5d10 6s2",
    electron_shells: [2, 8, 18, 32, 18, 2],
    color: "#94A3B8"
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomic_mass: 204.38,
    category: "post-transition metal",
    group: 13,
    period: 6,
    phase: "Solid",
    summary: "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p1",
    electron_shells: [2, 8, 18, 32, 18, 3],
    color: "#94A3B8"
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomic_mass: 207.2,
    category: "post-transition metal",
    group: 14,
    period: 6,
    phase: "Solid",
    summary: "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p2",
    electron_shells: [2, 8, 18, 32, 18, 4],
    color: "#94A3B8"
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomic_mass: 208.98,
    category: "post-transition metal",
    group: 15,
    period: 6,
    phase: "Solid",
    summary: "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the p-block elements with chemical properties resembling its lighter group 15 siblings arsenic and antimony.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p3",
    electron_shells: [2, 8, 18, 32, 18, 5],
    color: "#94A3B8"
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomic_mass: 209,
    category: "post-transition metal",
    group: 16,
    period: 6,
    phase: "Solid",
    summary: "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium, though its metallic character resembles that of its horizontal neighbors in the periodic table: thallium, lead, and bismuth.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p4",
    electron_shells: [2, 8, 18, 32, 18, 6],
    color: "#94A3B8"
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomic_mass: 210,
    category: "metalloid",
    group: 17,
    period: 6,
    phase: "Solid",
    summary: "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p5",
    electron_shells: [2, 8, 18, 32, 18, 7],
    color: "#34D399"
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomic_mass: 222,
    category: "noble gas",
    group: 18,
    period: 6,
    phase: "Gas",
    summary: "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas. It occurs naturally in minute quantities as an intermediate step in the normal radioactive decay chains through which thorium and uranium slowly decay into lead and various other short-lived radioactive elements.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p6",
    electron_shells: [2, 8, 18, 32, 18, 8],
    color: "#FDE68A"
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomic_mass: 223,
    category: "alkali metal",
    group: 1,
    period: 7,
    phase: "Solid",
    summary: "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive; its most stable isotope, francium-223, has a half-life of only 22 minutes. It is the second most electropositive element, behind only caesium, and is the second rarest naturally occurring element.",
    electron_configuration: "[Rn] 7s1",
    electron_shells: [2, 8, 18, 32, 18, 8, 1],
    color: "#F87171"
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomic_mass: 226,
    category: "alkaline earth metal",
    group: 2,
    period: 7,
    phase: "Solid",
    summary: "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is silvery-white, but it readily reacts with nitrogen on exposure to air, forming a black surface layer of radium nitride.",
    electron_configuration: "[Rn] 7s2",
    electron_shells: [2, 8, 18, 32, 18, 8, 2],
    color: "#FBBF24"
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomic_mass: 227,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Actinium is a chemical element with symbol Ac and atomic number 89. It was first isolated by French chemist André-Louis Debierne in 1899. Friedrich Oskar Giesel independently isolated it in 1902.",
    electron_configuration: "[Rn] 6d1 7s2",
    electron_shells: [2, 8, 18, 32, 18, 9, 2],
    color: "#F472B6"
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomic_mass: 232.04,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Thorium is a weakly radioactive metallic chemical element with symbol Th and atomic number 90. Thorium is silvery and tarnishes black when exposed to air, forming thorium dioxide; it is moderately hard, malleable, and has a high melting point.",
    electron_configuration: "[Rn] 6d2 7s2",
    electron_shells: [2, 8, 18, 32, 18, 10, 2],
    color: "#F472B6"
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomic_mass: 231.04,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.",
    electron_configuration: "[Rn] 5f2 6d1 7s2",
    electron_shells: [2, 8, 18, 32, 20, 9, 2],
    color: "#F472B6"
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomic_mass: 238.03,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.",
    electron_configuration: "[Rn] 5f3 6d1 7s2",
    electron_shells: [2, 8, 18, 32, 21, 9, 2],
    color: "#F472B6"
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomic_mass: 237,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium named it after Neptune, the next planet after Uranus.",
    electron_configuration: "[Rn] 5f4 6d1 7s2",
    electron_shells: [2, 8, 18, 32, 22, 9, 2],
    color: "#F472B6"
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomic_mass: 244,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
    electron_configuration: "[Rn] 5f6 7s2",
    electron_shells: [2, 8, 18, 32, 24, 8, 2],
    color: "#F472B6"
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomic_mass: 243,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas.",
    electron_configuration: "[Rn] 5f7 7s2",
    electron_shells: [2, 8, 18, 32, 25, 8, 2],
    color: "#F472B6"
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomic_mass: 247,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie, both known for their research on radioactivity.",
    electron_configuration: "[Rn] 5f7 6d1 7s2",
    electron_shells: [2, 8, 18, 32, 25, 9, 2],
    color: "#F472B6"
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomic_mass: 247,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the Lawrence Berkeley National Laboratory where it was discovered in December 1949.",
    electron_configuration: "[Rn] 5f9 7s2",
    electron_shells: [2, 8, 18, 32, 27, 8, 2],
    color: "#F472B6"
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomic_mass: 251,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Californium is a radioactive transuranic chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory (then the University of California Radiation Laboratory), by bombarding curium with alpha particles.",
    electron_configuration: "[Rn] 5f10 7s2",
    electron_shells: [2, 8, 18, 32, 28, 8, 2],
    color: "#F472B6"
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomic_mass: 252,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.",
    electron_configuration: "[Rn] 5f11 7s2",
    electron_shells: [2, 8, 18, 32, 29, 8, 2],
    color: "#F472B6"
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomic_mass: 257,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Fermium is a synthetic element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared.",
    electron_configuration: "[Rn] 5f12 7s2",
    electron_shells: [2, 8, 18, 32, 30, 8, 2],
    color: "#F472B6"
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomic_mass: 258,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Mendelevium is a synthetic element with symbol Md and atomic number 101. It is a metallic radioactive transuranic element in the actinide series, usually synthesized by bombarding einsteinium with alpha particles. It was named after Dmitri Mendeleev, father of the periodic table of the chemical elements.",
    electron_configuration: "[Rn] 5f13 7s2",
    electron_shells: [2, 8, 18, 32, 31, 8, 2],
    color: "#F472B6"
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomic_mass: 259,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series.",
    electron_configuration: "[Rn] 5f14 7s2",
    electron_shells: [2, 8, 18, 32, 32, 8, 2],
    color: "#F472B6"
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomic_mass: 266,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    summary: "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.",
    electron_configuration: "[Rn] 5f14 7s2 7p1",
    electron_shells: [2, 8, 18, 32, 32, 8, 3],
    color: "#F472B6"
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomic_mass: 267,
    category: "transition metal",
    group: 4,
    period: 7,
    phase: "Solid",
    summary: "Rutherfordium is a synthetic chemical element with symbol Rf and atomic number 104, named after physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope is 267Rf, which has a half-life of approximately 1.3 hours.",
    electron_configuration: "[Rn] 5f14 6d2 7s2",
    electron_shells: [2, 8, 18, 32, 32, 10, 2],
    color: "#94A3B8"
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomic_mass: 268,
    category: "transition metal",
    group: 5,
    period: 7,
    phase: "Solid",
    summary: "Dubnium is a synthetic chemical element with symbol Db and atomic number 105. Dubnium is highly radioactive: the most stable known isotope, dubnium-268, has a half-life of about 28 hours. Dubnium does not occur naturally on Earth and is produced artificially.",
    electron_configuration: "[Rn] 5f14 6d3 7s2",
    electron_shells: [2, 8, 18, 32, 32, 11, 2],
    color: "#94A3B8"
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomic_mass: 269,
    category: "transition metal",
    group: 6,
    period: 7,
    phase: "Solid",
    summary: "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature. It is also radioactive; the most stable known isotope, 269Sg, has a half-life of approximately 3.1 minutes.",
    electron_configuration: "[Rn] 5f14 6d4 7s2",
    electron_shells: [2, 8, 18, 32, 32, 12, 2],
    color: "#94A3B8"
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomic_mass: 270,
    category: "transition metal",
    group: 7,
    period: 7,
    phase: "Solid",
    summary: "Bohrium is a synthetic chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of bohrium are highly radioactive; the most stable known isotope is 270Bh with a half-life of approximately 61 seconds.",
    electron_configuration: "[Rn] 5f14 6d5 7s2",
    electron_shells: [2, 8, 18, 32, 32, 13, 2],
    color: "#94A3B8"
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomic_mass: 269,
    category: "transition metal",
    group: 8,
    period: 7,
    phase: "Solid",
    summary: "Hassium is a synthetic chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope is 269Hs, which has a half-life of approximately 9.7 seconds.",
    electron_configuration: "[Rn] 5f14 6d6 7s2",
    electron_shells: [2, 8, 18, 32, 32, 14, 2],
    color: "#94A3B8"
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomic_mass: 278,
    category: "transition metal",
    group: 9,
    period: 7,
    phase: "Solid",
    summary: "Meitnerium is a synthetic chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element not found in nature that can be created in a laboratory). The most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds.",
    electron_configuration: "[Rn] 5f14 6d7 7s2",
    electron_shells: [2, 8, 18, 32, 32, 15, 2],
    color: "#94A3B8"
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomic_mass: 281,
    category: "transition metal",
    group: 10,
    period: 7,
    phase: "Solid",
    summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 12.7 seconds.",
    electron_configuration: "[Rn] 5f14 6d9 7s1",
    electron_shells: [2, 8, 18, 32, 32, 17, 1],
    color: "#94A3B8"
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomic_mass: 282,
    category: "transition metal",
    group: 11,
    period: 7,
    phase: "Solid",
    summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes.",
    electron_configuration: "[Rn] 5f14 6d10 7s1",
    electron_shells: [2, 8, 18, 32, 32, 18, 1],
    color: "#94A3B8"
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomic_mass: 285,
    category: "transition metal",
    group: 12,
    period: 7,
    phase: "Solid",
    summary: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can only be created in a laboratory. The most stable known isotope, copernicium-285, has a half-life of approximately 29 seconds.",
    electron_configuration: "[Rn] 5f14 6d10 7s2",
    electron_shells: [2, 8, 18, 32, 32, 18, 2],
    color: "#94A3B8"
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomic_mass: 286,
    category: "post-transition metal",
    group: 13,
    period: 7,
    phase: "Solid",
    summary: "Nihonium is a synthetic chemical element with symbol Nh and atomic number 113. It is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of 20 seconds.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p1",
    electron_shells: [2, 8, 18, 32, 32, 18, 3],
    color: "#94A3B8"
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomic_mass: 289,
    category: "post-transition metal",
    group: 14,
    period: 7,
    phase: "Solid",
    summary: "Flerovium is a synthetic chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p2",
    electron_shells: [2, 8, 18, 32, 32, 18, 4],
    color: "#94A3B8"
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomic_mass: 290,
    category: "post-transition metal",
    group: 15,
    period: 7,
    phase: "Solid",
    summary: "Moscovium is a synthetic chemical element with symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p3",
    electron_shells: [2, 8, 18, 32, 32, 18, 5],
    color: "#94A3B8"
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomic_mass: 293,
    category: "post-transition metal",
    group: 16,
    period: 7,
    phase: "Solid",
    summary: "Livermorium is a synthetic chemical element with symbol Lv and atomic number 116. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p4",
    electron_shells: [2, 8, 18, 32, 32, 18, 6],
    color: "#94A3B8"
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomic_mass: 294,
    category: "metalloid",
    group: 17,
    period: 7,
    phase: "Solid",
    summary: "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p5",
    electron_shells: [2, 8, 18, 32, 32, 18, 7],
    color: "#34D399"
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomic_mass: 294,
    category: "noble gas",
    group: 18,
    period: 7,
    phase: "Solid",
    summary: "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p6",
    electron_shells: [2, 8, 18, 32, 32, 18, 8],
    color: "#FDE68A"
  }
];
